### PR TITLE
Fix Rubocop dependencies and config

### LINKED ISSUE #648: Rubocop dev dependencies/scripts are broken
### Issue Details

The upgrade to ruby 2.7 (see PR #634) seems to have broken the repository's rubocop scripts.

The root cause seems to be rubocop/rubocop/issues/6621, which was fixed by rubocop/rubocop/pull/6470, which is apparently included in [rubocop v0.62.0](rubocop/rubocop/releases/tag/v0.62.0) (and [possibly](https://github.com/rubocop/rubocop/issues/6621#issuecomment-451812879) in [rubocop v0.61.0](rubocop/rubocop/releases/tag/v0.61.0)).

Also, note that v0.62 is almost 3 years old now, and the latest release is [rubocop v1.23.0](rubocop/rubocop/releases/tag/v1.23.0). So it may be better to upgrade to a more recent release (than v0.62).

### Logs (*Please redact all sensitive information in your logs*)

```
% rubocop
unknown keywords: :whitelist_classes, :whitelist_symbols
```

### Repro steps (*if necessary, delete otherwise*)

1. Followed the env setup instructions in 'docs/development.md'.
2. run `rubocop` or `pushd 'src/bosh_azure_cpi' ; ./bin/rubocop_check ; popd`

### PR DESCRIPTION
**Pull request by Justin-W**
- [x] Please check this box and fill the data as below once you have run the unit tests.
      Code coverage should keeps at 100%. 

  **_NOTE:_** This PR changes no code _or_ tests, just config files and MD docs, and there is no change to coverage metrics. (The drop to `4182 / 4203 LOC (99.5%) covered` is due to previous PRs.)

  ```
  pushd src/bosh_azure_cpi
    ./bin/test-unit
  popd
  
  ...[verbose spec output omitted for brevity]...
  
  Finished in 5 seconds (files took 0.76917 seconds to load)
  972 examples, 0 failures
  
  Coverage report generated for RSpec to /Users/justinw/go/src/github.com/cloudfoundry/bosh-azure-cpi-release/src/bosh_azure_cpi/coverage. 4182 / 4203 LOC (99.5%) covered.
  ```

### Rubocop output

  **_NOTE:_** The following is the new output from rubocop. Previously, executing rubocop failed with errors. After fixing the errors, hundreds of cop offenses in existing (unchanged) code were being reported, so the `.rubocop_todo.yml` config was updated to ignore them to reset the current codebase to a new baseline of zero offenses.

  ```
  cd src/bosh_azure_cpi
  rubocop --regenerate-todo
  Phase 1 of 2: run Layout/LineLength cop
  Inspecting 184 files
  .C...CCCC..C...CCC..CC.....CCC.C.C.CCCCCCCCCCCC.CCCCCCC.CC.C.CCCCCC....C.C..CCC.CCCCCCCCCCC.CCCCCCCCCCCCC.CC.C.C..............C.CCC.CC.C..CC.C..C..CCC.CCCCC....CCCCCCC.CCCCCCCCCCCCCCCC
  
  184 files inspected, 858 offenses detected, 493 offenses auto-correctable
  Created .rubocop_todo.yml.
  Phase 2 of 2: run all cops
  Inspecting 184 files
  CCC.CWCCWCCCCCCCCCCCCCCCCCCCCCCCCWCCCCWCWCWCCCW.CWCCCCCCCCCCCCCCCCCCCCCCCWCCWCWCCCCWCWCCWWWWCCCWCCCCWWWWWWWCCWCCCCCCCCCCCCCCWCCCWWWCWWCWCCCWCCWCWCWWWWWWWCCCCCWCCCWWCCCCWCCWCCCCCWCCCCCC
  
  184 files inspected, 7454 offenses detected, 1969 offenses auto-correctable
  Created .rubocop_todo.yml.
  ```

  ```
  cd src/bosh_azure_cpi
  ./bin/rubocop_check
  ~/go/src/github.com/cloudfoundry/bosh-azure-cpi-release/src/bosh_azure_cpi ~/go/src/github.com/cloudfoundry/bosh-azure-cpi-release/src/bosh_azure_cpi
  Running rubocop with Ruby version ruby-2.7.3...
  Inspecting 184 files
  ........................................................................................................................................................................................
  
  184 files inspected, no offenses detected
  
  ~/go/src/github.com/cloudfoundry/bosh-azure-cpi-release/src/bosh_azure_cpi
  ```

  NOTE: Please see how to setup dev environment and run unit tests in docs/development.md.

### Changelog

* Fixes #648
* Updated rubocop to latest version (v1.23)
* Updated rubocop dependencies in gem config
* Updated rubocop config to enable new cops
* Updated .rubocop_todo.yml rubocop config to ignore all existing cop offenses
* Updated `docs/development.md` with new rubocop-related instructions
* Enabled rubocop-recommended rubocop extensions: rubocop-rake, rubocop-rspec

### CODE REVIEW

**Comment by Justin-W** [comment]
FYI: Added some additional commits to enable rubocop-recommended rubocop extensions: rubocop-rake, rubocop-rspec. Also updated the changelog in the PR's description accordingly.

**Comment by Justin-W** [comment]
@bgandon @friegger Any thoughts on this?

**Comment by RobertBoyd** [comment]
Is there any update on progress for this PR?

**Review by ramonskie — APPROVED** [review]
lgtm

**Review by rkoster — APPROVED** [review]
LGTM

**Comment by rkoster** [comment]
Thanks @Justin-W

**Pull request merged**
