### PR TITLE
don't run "_init_azure" for every CPI method

### PR DESCRIPTION
**Pull request by bingosummer**
- [x] Please check this box and fill the data as below once you have run the unit tests.
      Code coverage should keeps at 100%. 

  ```
  pushd src/bosh_azure_cpi
    ./bin/test-unit
  popd
  ```

  NOTE: Please see how to setup dev environment and run unit tests in docs/development.md.

### Changelog

* don't run "_init_azure" for every CPI method

### CODE REVIEW

**Comment by ahelal** [comment]
any update on merging this PR @h4xnoodle  ?

**Comment by MSSedusch** [comment]
@ahelal did some tests and this PR further reduces the GET calls towards the Azure API and would further reduce the risk for getting throttled.

Current CPI version without storage account configuration:
60 calls for List resources in resource group calls
59 calls for Get Storage Account Keys
54 calls for List Storage Account

Current CPI version with storage account configuration:
58 calls for Get Storage Account 
58 calls for Get Storage Account Keys 

CPI with this PR and storage account configuration:
31 calls for Get Storage Account 
31 calls for Get Storage Account Keys 

This PR reduces the most frequent API calls by almost 50%. @h4xnoodle can you please review, merge and create a new CPI release with this PR?

Thanks

**Comment by friegger** [comment]
@aashah Who can merge this, have a quick look at the CPI pipelines and cut a release?

**Comment by ClaudiaBaur** [comment]
@aashah,  @h4xnoodle, any chance to merge this PR soon?

**Comment by aashah** [comment]
Rebecca and I are no longer working with Pivotal/contributing to CloudFoundry & BOSH.

/cc @dlresende

**Comment by dsboulder** [comment]
We think this works, but it's possible some obscure CPI call is now forgetting to run init. Merging with @mrosecrance and seeing how it fairs in CI.

**Comment by mrosecrance** [comment]
Reverting temporarily. This commit broke a few integration tests that make the assumption that init will always be run to form child objects to make assertions against. CI is also red for unrelated reasons, so planning on fixing those first then reapplying this commit, then fixing the tests.

**Comment by dlresende** [comment]
Also I believe we were merging against develop instead of master.

**Pull request merged**
