### PR TITLE
Update development.md with additional `chruby` setup info

### PR DESCRIPTION
**Pull request by Justin-W**
Note: This repo's dev scripts impose specific constraints about the location at which `chruby` is installed (see [this script code](https://github.com/cloudfoundry/bosh-azure-cpi-release/blob/ca6886a8b43ffbe56a44b594ec2a73af745ab77d/src/bosh_azure_cpi/bin/check-ruby-version#L3-L5)). Those constraints were previously undocumented within [docs/development.md](https://github.com/cloudfoundry/bosh-azure-cpi-release/blob/master/docs/development.md). This PR makes them explicit.

---

- [x] Please check this box and fill the data as below once you have run the unit tests.
      Code coverage should keeps at 100%. 

  **_NOTE:_** This PR changes no code _or_ tests, just MD docs. So I'm assuming that the drop to `4182 / 4203 LOC (99.5%) covered` is due to some previous PR.

  ```
  pushd src/bosh_azure_cpi
    ./bin/test-unit
  popd
  
  ...[verbose spec output omitted for brevity]...
  
  Top 10 slowest examples (2.16 seconds, 42.1% of total time):
    Bosh::AzureCloud::Helpers#flock for multiple processes with exclusive lock the processes should get the lock sequentially and then call the block
      1.02 seconds ./spec/unit/helpers_spec.rb:930
    Bosh::AzureCloud::Helpers#flock for multiple processes with share lock the processes should get the lock in parallel and then call the block
      0.51163 seconds ./spec/unit/helpers_spec.rb:959
    Bosh::AzureCloud::TelemetryEventList#format_data_for_wire_server should return with right value
      0.14532 seconds ./spec/unit/telemetry/telemetry_event_list_spec.rb:47
    Bosh::AzureCloud::Helpers#flock for multiple processes with exclusive but no block lock only the process gets the lock and calls the block, the other process should return directly
      0.11444 seconds ./spec/unit/helpers_spec.rb:987
    Bosh::AzureCloud::BlobManager#create_page_blob when empty page blob should not call put_blob_pages
      0.07435 seconds ./spec/unit/blob_manager_spec.rb:209
    Bosh::AzureCloud::BlobManager#create_empty_page_blob when container not exists when other one created the container should use the created container
      0.05982 seconds ./spec/unit/blob_manager_spec.rb:288
    Bosh::AzureCloud::BlobManager#create_page_blob when normal page blob when uploading page blob succeeds raise no error
      0.05972 seconds ./spec/unit/blob_manager_spec.rb:160
    Bosh::AzureCloud::BlobManager#get_blob_properties when storage account does not exist should raise error
      0.05947 seconds ./spec/unit/blob_manager_spec.rb:404
    Bosh::AzureCloud::BlobManager#get_blob_size_in_bytes gets the size of the blob
      0.05927 seconds ./spec/unit/blob_manager_spec.rb:124
    Bosh::AzureCloud::BlobManager#create_vhd_page_blob when creating vhd page blob failed page blob created page blob should be deleted
      0.05921 seconds ./spec/unit/blob_manager_spec.rb:375  

  Top 10 slowest example groups:
    Bosh::AzureCloud::BlobManager
      0.04412 seconds average (1.76 seconds / 40 examples) ./spec/unit/blob_manager_spec.rb:4
    Bosh::AzureCloud::TelemetryEventList
      0.0365 seconds average (0.14601 seconds / 4 examples) ./spec/unit/telemetry/telemetry_event_list_spec.rb:5
    Bosh::AzureCloud::VMManager
      0.02061 seconds average (0.06184 seconds / 3 examples) ./spec/unit/vm_manager/create/use_config_disk_spec.rb:9
    Bosh::AzureCloud::Helpers
      0.02022 seconds average (1.68 seconds / 83 examples) ./spec/unit/helpers_spec.rb:5
    Bosh::AzureCloud::AzureClient
      0.00945 seconds average (0.0189 seconds / 2 examples) ./spec/unit/azure_client/update_tags_of_storage_account_spec.rb:8
    Bosh::AzureCloud::CPILogger
      0.00873 seconds average (0.00873 seconds / 1 example) ./spec/unit/logger_spec.rb:5
    Bosh::AzureCloud::AzureClient
      0.00624 seconds average (0.01871 seconds / 3 examples) ./spec/unit/azure_client/create_resource_group_spec.rb:8
    Bosh::AzureCloud::AzureClient
      0.00581 seconds average (0.01162 seconds / 2 examples) ./spec/unit/azure_client/request_headers_spec.rb:8
    Bosh::AzureCloud::AzureClient
      0.00469 seconds average (0.02343 seconds / 5 examples) ./spec/unit/azure_client/attach_disk_to_virtual_machine_spec.rb:8
    Bosh::AzureCloud::AzureClient
      0.00444 seconds average (0.0311 seconds / 7 examples) ./spec/unit/azure_client/create_storage_account_spec.rb:8  

  Finished in 5.12 seconds (files took 1.59 seconds to load)
  972 examples, 0 failures  

  Coverage report generated for RSpec to /Users/justinw/go/src/github.com/cloudfoundry/bosh-azure-cpi-release/src/bosh_azure_cpi/coverage. 4182 / 4203 LOC (99.5%) covered.
  ~/go/src/github.com/cloudfoundry/bosh-azure-cpi-release/src/bosh_azure_cpi
  ```

  NOTE: Please see how to setup dev environment and run unit tests in docs/development.md.

### Changelog

* Updated development.md with additional `chruby` setup info

### CODE REVIEW

**Comment by ramonskie** [comment]
i personally would just remove the whole chruby as we only set 1 ruby version anyways
for example we also got rid of it in our stemcell builder process
https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/8a82cc210fdf755b0fb7a3f211c43398f00bf4fe

**Comment by Justin-W** [comment]
> i personally would just remove the whole chruby as we only set 1 ruby version anyways

That sounds like a larger change. There are currently 36 code references to `chruby` across 9 files. Many of those refs are in 6 CI-related files, including the `Dockerfile` and platform-specific scripts for both windows and non-windows, and including scripts related to the CI integration and BATS tests.

I don't have a CPI CI env set up to test any changes to the CI process/scripts. So even if I were to try to eliminate the `chruby` dependency (as @ramonskie advocated above), I'd have no way to verify whether my changes broke anything in the CI env.

With this PR, I was only intending to update the dev env setup instructions to accurately reflect the existing dev env and processes, so I could work on a feature enhancement.

@ramonskie Are you OK with this PR as-is for now?

@KaiHofstetter @friegger Any thoughts?

**Comment by ramonskie** [comment]
@Justin-W yes i'm okay with this..
it was just a suggestion

**Review by ramonskie — APPROVED** [review]

**Review by rkoster — APPROVED** [review]

**Comment by rkoster** [comment]
Thanks @Justin-W

**Pull request merged**
