### PR TITLE
Az pv2 disks

### PR DESCRIPTION
**Pull request by MSSedusch**
# Checklist:

Please check each of the boxes below for which you have completed the corresponding task:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] All unit tests pass locally (after my changes)
- [x] Rubocop reports zero offenses (after my changes)

Please include below the summary portions of the output from the following 2 scripts:

  ```
  pushd src/bosh_azure_cpi
    ./bin/test-unit
    ./bin/rubocop_check
  popd
  ```

  _NOTE:_ Please see how to setup dev environment and run unit tests in docs/development.md.

### Unit Test output:

```
Finished in 8.54 seconds (files took 4.79 seconds to load)
1031 examples, 0 failures

Coverage report generated for RSpec to /workspaces/dev_bosh-azure-cpi-release/bosh-azure-cpi-release/src/bosh_azure_cpi/coverage. 4257 / 4289 LOC (99.25%) covered.
/workspaces/dev_bosh-azure-cpi-release/bosh-azure-cpi-release/src/bosh_azure_cpi
```

### Rubocop output:

```
Running rubocop with Ruby version ...
Inspecting 189 files
W...............................C...............C............................................................................................................................................

Offenses:

Gemfile:16:11: W: [Correctable] Lint/ParenthesesAsGroupedExpression: (...) interpreted as grouped expression.
install_if (-> { (`uname`.include?('Linux') && !(`lsb_release -sr`.include?('16.04') if system('which lsb_release > /dev/null 2>&1'))) || `gcc -dumpversion`.to_i > 6 }) do
          ^
lib/cloud/azure/restapi/azure_client.rb:2722:7: C: [Correctable] Style/IfUnlessModifier: Favor modifier if usage when having a single-line body. Another good alternative is the usage of control flow &&/||.
      if vm['identity'] && vm['identity']['type'] == 'UserAssigned'
      ^^
lib/cloud/azure/restapi/azure_client.rb:2723:98: C: [Correctable] Style/EachWithObject: Use each_with_object instead of inject.
        vm['identity']['userAssignedIdentities'] = vm['identity']['userAssignedIdentities'].keys.inject({}) { |result, k| result[k] = {}; result }
                                                                                                 ^^^^^^
lib/cloud/azure/restapi/azure_client.rb:2723:137: C: [Correctable] Style/Semicolon: Do not use semicolons to terminate expressions.
        vm['identity']['userAssignedIdentities'] = vm['identity']['userAssignedIdentities'].keys.inject({}) { |result, k| result[k] = {}; result }
                                                                                                                                        ^
lib/cloud/azure/vms/vm_manager.rb:21:5: C: Metrics/AbcSize: Assignment Branch Condition size for create is too high. [<87, 177, 52> 204/192]
    def create(bosh_vm_meta, location, vm_props, disk_cids, network_configurator, env, agent_settings, network_spec, config) ...
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/cloud/azure/vms/vm_manager.rb:21:5: C: Metrics/CyclomaticComplexity: Cyclomatic complexity for create is too high. [44/39]
    def create(bosh_vm_meta, location, vm_props, disk_cids, network_configurator, env, agent_settings, network_spec, config) ...
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/cloud/azure/vms/vm_manager.rb:21:5: C: Metrics/MethodLength: Method has too many lines. [189/184]
    def create(bosh_vm_meta, location, vm_props, disk_cids, network_configurator, env, agent_settings, network_spec, config) ...
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/cloud/azure/vms/vm_manager.rb:21:5: C: Metrics/PerceivedComplexity: Perceived complexity for create is too high. [49/45]
    def create(bosh_vm_meta, location, vm_props, disk_cids, network_configurator, env, agent_settings, network_spec, config) ...
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

189 files inspected, 8 offenses detected, 4 offenses auto-correctable
rubocop find some issues.
/workspaces/dev_bosh-azure-cpi-release/bosh-azure-cpi-release/src/bosh_azure_cpi
```

# Changelog
* Add support for Premium V2 disks

### CODE REVIEW

**Review by lnguyen — CHANGES_REQUESTED** [review]
LGTM, do you mind squashing commits to one?

**Comment by MSSedusch** [comment]
Thanks for reviewing @lnguyen . I am running an E2E test at the moment, will squash once I finish the test :)

**Comment by MSSedusch** [comment]
@lnguyen E2E tests were successful. I squashed the commits. Thanks

**Comment by jpalermo** [comment]
Thanks! We'll try to get a new release of this cut soon.

**Comment by cunnie** [comment]
Hey @MSSedusch :

Could you please fix the error that this change is causing in our CI (continuous integration)? We can't cut a new release until this problem is fixed. Thanks!

Here's the error from one of the failing tests (several tests are failing, but the error is the same in all of them):

```json
{
  "error": {
    "code": "NoRegisteredProviderFound",
    "message": "No registered resource provider found for location 'eastus2' and API version '2021-11-01' for type 'snapshots'. The supported api-versions are '2016-04-30-preview, 2017-03-30, 2018-04-01, 2018-06-01, 2018-09-30, 2019-03-01, 2019-07-01, 2019-11-01, 2020-05-01, 2020-06-30, 2020-09-30, 2020-12-01, 2021-04-01, 2021-08-01, 2021-12-01, 2022-03-02, 2022-07-02, 2023-01-02, 2023-04-02, 2023-10-02'. The supported locations are 'southeastasia, eastus2, centralus, westeurope, eastus, northcentralus, southcentralus, westus, northeurope, eastasia, brazilsouth, westus2, westcentralus, ukwest, uksouth, japaneast, japanwest, canadacentral, canadaeast, centralindia, southindia, australiaeast, australiasoutheast, koreacentral, koreasouth, westindia, francecentral, southafricanorth, uaenorth, australiacentral, switzerlandnorth, germanywestcentral, norwayeast, jioindiawest, westus3, swedencentral, qatarcentral, polandcentral, italynorth, israelcentral'."
  }
}
```

And here's the stack trace:

```
     # ./lib/cloud/azure/restapi/azure_client.rb:2504:in `check_completion'
     # ./lib/cloud/azure/restapi/azure_client.rb:2591:in `http_put'
     # ./lib/cloud/azure/restapi/azure_client.rb:1216:in `create_managed_snapshot'
     # ./lib/cloud/azure/disk/disk_manager2.rb:135:in `snapshot_disk'
     # ./lib/cloud/azure/cloud.rb:739:in `block (2 levels) in snapshot_disk'
     # ./lib/cloud/azure/telemetry/telemetry_manager.rb:71:in `monitor'
     # ./lib/cloud/azure/cloud.rb:732:in `block in snapshot_disk'
     # ./lib/cloud/azure/cloud.rb:731:in `snapshot_disk'
     # ./spec/integration/resources/availability_sets_spec.rb:57:in `block (6 levels) in <top (required)>'
     # ./spec/integration/spec_helper.rb:104:in `vm_lifecycle'
     # ./spec/integration/resources/availability_sets_spec.rb:42:in `block (5 levels) in <top (required)>'
```

We think this is the change that caused the problem: <https://github.com/cloudfoundry/bosh-azure-cpi-release/blame/1004194fb3a68b3ee49f860c7feec28640305246/src/bosh_azure_cpi/lib/cloud/azure/utils/helpers.rb#L19>

You might be able to find instructions to run the integration tests [here](https://github.com/cloudfoundry/bosh-azure-cpi-release/blob/master/docs/development.md), though they may be woefully out-of-date.

**Comment by MSSedusch** [comment]
@cunnie will look into it. Thanks

**Comment by MSSedusch** [comment]
@cunnie I tried to follow the README to set up a dev build pipeline. When I run the pipeline in Concourse, I get the following error. Can you help me to resolve it?

http://x.x.x.x:8080/teams/main/pipelines/bosh-azure-cpi-develop/jobs/build-candidate/builds/3
```
Digest: sha256:6f9917093e5bf50c7af9a8793369453fb53db5cacae9e54ff65dbedef9e6f3e1
Status: Downloaded newer image for boshcpi/azure-cpi-release@sha256:6f9917093e5bf50c7af9a8793369453fb53db5cacae9e54ff65dbedef9e6f3e1

Successfully pulled boshcpi/azure-cpi-release@sha256:6f9917093e5bf50c7af9a8793369453fb53db5cacae9e54ff65dbedef9e6f3e1.

ls: cannot access '/opt/rubies': Operation not permitted
running unit tests
bosh-cpi-src/ci/tasks/build-candidate.sh: line 14: bundle: command not found
```

**Comment by jpalermo** [comment]
Running the integration tests is mostly a nightmare. We went ahead and fixed the breakage; it was caused by the new version of the compute API not having a compatible compute/storage API version. Unfortunately there isn't an API version that supports both Snapshots, other compute stuff, and PV2 disks so we had to split Snapshots out into a separately tracked API version.

Seems to work though. All should be released in v47.0.0 which is now available.

**Comment by beyhan** [comment]
Thanks for the update @jpalermo!

**Comment by MSSedusch** [comment]
@jpalermo I was able to execute the integration tests yesterday on my local dev machine, without concourse. I wanted to start working on the fix today, was positively surprised this morning that you already made the fix and released a new version. Thank you very much! :)

**Comment by jpalermo** [comment]
Hey @MSSedusch , we found a small bug in the current release, if you don't specify ephemeral_disk at all, you get an "undefined method :[] for nil" as it looks for ips || mpbs. We're going to fix this today, but be aware that the bug currently exists.

Also, could you create a PR to document these new properties for [bosh.io](https://bosh.io/docs/azure-cpi/#resource-pools)?

The docs repo is [here](https://github.com/cloudfoundry/docs-bosh/blob/master/content/azure-cpi.md)

**Comment by MSSedusch** [comment]
@jpalermo done - https://github.com/cloudfoundry/docs-bosh/pull/822
Thanks for fixing the regression!

**Pull request merged**
