### PR TITLE
Delete the deprecated user image only once

### PR DESCRIPTION
**Pull request by gossion**

### CODE REVIEW

**Comment by andyliuliming** [comment]
@gossion could you please explain more about this?

I guess the this change is for when the stemcell user_image_name not exists, and user_image_name_deprecated exist. then some migration action should be taken.
and you are worrying that the delete_user_image action may be taken more than one time.

but seems L64 L65 already handled this case. so the double deleting seems may not happen.

please correct me if the change is for another intention.

thanks.

**Comment by gossion** [comment]
this can be done in multiple process. Think about process A, B in L99, then A takes the lock to delete -> create new image, after that process B should not delete the image again.

**Comment by andyliuliming** [comment]
> This can be done in multiple process. Think about: process A, B in L99, then A takes the lock to delete -> create new image, after that process B should not delete the image again.

bug we have flock("#{CPI_LOCK_CREATE_USER_IMAGE}-#{user_image_name}", File::LOCK_EX)

**Comment by andyliuliming** [comment]
> This can be done in multiple process. Think about: process A, B in L99, then A takes the lock to delete -> create new image, after that process B should not delete the image again.

ok, got your point, then I think we'd better to handle the copy blob 
too, the copy blob can be did by two process too. 
so based on this, I think we'd better to expand the lock scope for this case. then things will be some simpler.

**Comment by bingosummer** [comment]
Since `delete_user_image` doesn't raise an error if the user image doesn't exist, so I simply delete the deprecated image name every time. I agree that it's better to delete the image only once.

**Comment by andyliuliming** [comment]
@gossion if you do not want to do this change for this time, please help file one issue to track this. or tell me to file it : )

**Comment by gossion** [comment]
@andyliuliming , the action to copy blob does not have the same problem.

**Pull request merged**
