### PR TITLE
Bump nokogiri with security fixes

### PR DESCRIPTION
**Pull request by fearoffish**
# Checklist:

Please check each of the boxes below for which you have completed the corresponding task:

- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added tests that prove my fix is effective or that my feature works
- [x] All unit tests pass locally (after my changes)
- [x] Rubocop reports zero offenses (after my changes)

### Unit Test output:

```
Finished in 5.56 seconds (files took 1.18 seconds to load)
1023 examples, 0 failures
```

### Rubocop output:

```
Inspecting 190 files
..............................................................................................................................................................................................

190 files inspected, no offenses detected
```

# Changelog

* Bumped Nokogiri to 1.13.8
* Fixed spec files that did not meet rubocop requirements

### CODE REVIEW

**Review by mvach — APPROVED** [review]

**Review by rkoster — APPROVED** [review]

**Review by rkoster — CHANGES_REQUESTED** [review]
@fearoffish Could you fix the easycla check? It looks like your git identity does not match what you have setup on your github account.

**Comment by rkoster** [comment]
ping @fearoffish

**Comment by fearoffish** [comment]
Urgh, I've clicked the EasyCLA link and filled in the email address for the commit, as well as signed it. What am I missing?!

**Review by rkoster — APPROVED** [review]

**Review by ramonskie — APPROVED** [review]

**Comment by cunnie** [comment]
@fearoffish Thanks! Next time, could you please vendor the gems by running `bin/vendor_gems` before submitting the PR? You'll be our hero!

**Pull request merged**
