### PR TITLE
Add support for multiple load balancers

### PR DESCRIPTION
**Pull request by MSSedusch**
- [x] Please check this box and fill the data as below once you have run the unit tests.
      Code coverage should keeps at 100%. 

  ```
  pushd src/bosh_azure_cpi
    ./bin/test-unit
  popd
  ```

  NOTE: Please see how to setup dev environment and run unit tests in docs/development.md.

### Changelog

* add support for multiple load balancers

### CODE REVIEW

**Comment by klakin-pivotal** [comment]
Thanks for the PR!

We'll merge it and run it through our test suite. Will let you know if our tests don't like the change.

**Comment by plowin** [comment]
Hi @klakin-pivotal , what was the result of the testing? Can this be released soon?

**Comment by klakin-pivotal** [comment]
Thanks for reminding me about this. This passed our tests in CI, and now I need to find the docs that tell me how to create a new release.

**Comment by klakin-pivotal** [comment]
There is a new release on both `bosh.io` and here in Github. Do let us know if you have any trouble with them.

**Pull request merged**
