### PR TITLE
Improve JSON parsing speed by using FastJsonParser

### PR DESCRIPTION
**Pull request by mvach**
https://github.com/cloudfoundry/bosh-azure-cpi-release/issues/667

# Checklist:

Please check each of the boxes below for which you have completed the corresponding task:

- :white_check_mark: I have performed a self-review of my own code
- :white_circle: I have commented my code, particularly in hard-to-understand areas
- :white_circle: I have added tests that prove my fix is effective or that my feature works
- :white_check_mark: All unit tests pass locally (after my changes)
- :white_check_mark: Rubocop reports zero offenses (after my changes)

Please include below the summary portions of the output from the following 2 scripts:

  ```
  pushd src/bosh_azure_cpi
    ./bin/test-unit
    ./bin/rubocop_check
  popd
  ```

### Unit Test output:

> Finished in 10.53 seconds (files took 5.74 seconds to load)
> 1023 examples, 0 failures

### Rubocop output:

> 190 files inspected, no offenses detected

# Changelog

* Improve JSON parsing speed by using FastJsonParser

### CODE REVIEW

**Comment by mvach** [comment]
There is one leftover that is not migrated to fast_jsonparser since it isn't a simple replacement: https://github.com/cloudfoundry/bosh-azure-cpi-release/blob/2aeb7bd3ed5e47d10a4fad22f49f142ff05ca14b/docs/advanced/configure-cf-external-databases-using-azure-mysql-postgres-service/migrate-mysql-databases/migrate-mysql-databases.rb#L126

But since it is a script in the docs from 2018 and for mysql I'm currently guessing that it is acceptable to keep it like it is.

**Review by fearoffish — APPROVED** [review]
lgtm

**Comment by nouseforaname** [comment]
What's the speed improvement in practice?

**Review by rkoster — APPROVED** [review]

**Review by nouseforaname — APPROVED** [review]
Thanks for the perf info. Lgtm

**Pull request merged**
