### PR TITLE
Implement API method resize_disk for managed disks

### PR DESCRIPTION
**Pull request by vicwicker**
# Checklist:

Please check each of the boxes below for which you have completed the corresponding task:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] All unit tests pass locally (after my changes)
- [x] Rubocop reports zero offenses (after my changes)

### Unit Test output:

```
Finished in 12.4 seconds (files took 1.2 seconds to load)
1020 examples, 0 failures

Coverage report generated for RSpec to /root/workspace/bosh-azure-cpi-release/src/bosh_azure_cpi/coverage. 4277 / 4296 LOC (99.56%) covered.
~/workspace/bosh-azure-cpi-release/src/bosh_azure_cpi
```

### Rubocop output:

```
Offenses:

lib/cloud/azure/restapi/azure_client.rb:25:3: C: Metrics/ClassLength: Class has too many lines. [1664/1645]
  class AzureClient ...
  ^^^^^^^^^^^^^^^^^
spec/unit/azure_client/get_operation_spec.rb:8:1: C: Metrics/BlockLength: Block has too many lines. [2219/2197]
describe Bosh::AzureCloud::AzureClient do ...
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

187 files inspected, 2 offenses detected
```

# Changelog

* This change allows to resize managed disks on Azure.
* Downsizing is not supported by Azure so in this case we still fall back to the strategy of creating a new disk and copying data.
* Analogous change to: https://github.com/cloudfoundry/bosh-aws-cpi-release/commit/91a701e150b02c31fd1887e217fb5e7c09744cb3 and https://github.com/cloudfoundry/bosh-openstack-cpi-release/commit/d081938852ecae502c0ba285020996a4a0c0d01d

### CODE REVIEW

**Comment by beyhan** [comment]
@vicwicker can you please sign the CLA?

**Review by lnguyen — CHANGES_REQUESTED** [review]
Looks good overall, it might be hard to test but can you write some integration tests? If anything if it fails in pipelines we(BOSH team) will fix it

**Comment by vicwicker** [comment]
> Looks good overall, it might be hard to test but can you write some integration tests? If anything if it fails in pipelines we(BOSH team) will fix it

@lnguyen I added a integration test: https://github.com/cloudfoundry/bosh-azure-cpi-release/pull/660/commits/5a70b1aa93b38b6a317d84ac86e086bb7a6b25f6

Other behaviours raise a `Bosh::Clouds::NotSupported` exception and I think that's covered by the unit tests and would become redundant with an integration test. 

The summary of the new integration test is:

```
# bundle exec rspec spec/integration/managed_disks_spec.rb --format documentation
...
I, [2022-02-17T08:41:27.191922 #365 #5520] INFO --: Create new managed disk with 10000 MiB
...
I, [2022-02-17T08:41:33.215034 #365 #5520] INFO --: Resize managed disk 'caching:None;disk_name:bosh-disk-data-eb3f7caf-088e-4d0e-b8ad-922d458cf26d;resource_group_name:<redacted>' to 20000 MiB
... 
I, [2022-02-17T08:41:39.270051 #365 #5520] INFO --: Delete managed disk 'caching:None;disk_name:bosh-disk-data-eb3f7caf-088e-4d0e-b8ad-922d458cf26d;resource_group_name:<redacted>'
...
Finished in 20.23 seconds (files took 0.45375 seconds to load)
1 example, 0 failures
```

**Comment by beyhan** [comment]
In https://github.com/cloudfoundry/bosh-aws-cpi-release/pull/123 we had some findings in the AWS CPI resize implementation which could be useful here. Just adding it as context.

**Review by lnguyen — APPROVED** [review]
LGTM

**Comment by vicwicker** [comment]
Is there anything left to do here or could we maybe merge this? Thanks!

**Comment by beyhan** [comment]
There is still one review open. We have a police to have two reviews per pr.

**Review by jpalermo — APPROVED** [review]
Sorry for the delay. Looks great. Thanks!

**Pull request merged**
